### ISSUE TITLE
Crash on unwrap()

### ISSUE THREAD

**Issue by makorne** [malaire/ml-downloader#1]
Hi! 
Thank you for your interesting crate!

I tried it with the updated code from hhtpmock example for a simple get json request :

[example](https://github.com/alexliesenfeld/httpmock/blob/master/tests/examples/json_body_tests.rs)

```
    let m = server.mock(|when, then| {
        when.method(GET)
            .path("/users");
        then.status(200)
            .header("content-type", "application/json")
            .json_body(json!({ "name": "Hans" }));
    });
```
The request:

```
    let mut response = Request::get(&format!("http://{}/users", server.address()))
        .body(())
        .unwrap()
        .send()
        .unwrap();

    let user: Value =
        serde_json::from_str(&response.text().unwrap()).expect("cannot deserialize JSON");
```
        
Works well.    

But 

```
let mut downloader = Downloader::builder()
                .reqwest(|cb| cb.user_agent("foobar/1.0"))
                .interval(1.0, 1.1)
                .retry_delays(&[(2.0, 2.2), (5.0, 5.5)])
                .build().expect("Cant build Downloader");
            let bytes = downloader.get(&url).send().expect("Cant download");
```
            
crashed:

`thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Option::unwrap()` on a `None` valuecalled `Option::unwrap()` on a `None` value', ', .cargo/registry/src/index.crates.io-6f17d22bba15001f/ml-downloader-0.1.0/src/lib.rs/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ml-downloader-0.1.0/src/lib.rs::398398::4747`
            
            
```
    fn send_once(&mut self) -> Result<Bytes, Error> {
        let response = self.inner.try_clone().unwrap().send()?;     << This unwrap()
```
        
I don`t know why but now the response is None... 
Anyway, it looks like a better solution to remove this unwrap and respond with some Error code to prevent crashing .

Cheers!

**Comment by malaire** [comment]
Strange ... That line is attempting to clone `reqwest::blocking::RequestBuilder` and according to documentation that should return `None` only when body of the request can't be cloned, i.e. if it's a stream.

**Comment by malaire** [comment]
Checking through the code I don't see any way for request body to be stream. Code never sets request body and `reqwest::blocking::RequestBuilder` is kept private and never exposed.

**Comment by malaire** [comment]
I've now gone through `reqwest` source code.

`ml-downloader` basically does just `client.get(url).try_clone().unwrap()`. According to `reqwest` documentation and source code, this sets request body to `null` and then `try_clone` can't return `None` so the `unwrap` can't fail.

So the only reason I can think of for this to fail would be some kind of memory corruption (e.g. because of some unsafe code elsewhere).

**Comment by malaire** [comment]
Actually I just realized that it's not well documented how this works if `url` is invalid, I'll look into that.

**Comment by malaire** [comment]
Sorry, I missed a small undocumented detail when checking `reqwest` source code:

```
// impl RequestBuilder
pub fn try_clone(&self) -> Option<RequestBuilder> {
        self.request
            .as_ref()
            .ok()
            .and_then(|req| req.try_clone())
            .map(|req| RequestBuilder {
                client: self.client.clone(),
                request: Ok(req),
            })
    }
```

That `.ok()` there makes this return `None` if given `url` can't be parsed.

**Comment by malaire** [comment]
This turns out to be a bit tricky to fix since `try_clone` hides the underlying error. I'll wait for comments on the `reqwest` issue (https://github.com/seanmonstar/reqwest/issues/1943) I created before deciding what to do.

But for now just check that your `url` is valid and you shouldn't get this crash.

**Comment by makorne** [comment]
You are right!! 
I already found it, the error because double quotes from serde_json Value like` "\"http://site.com\""`
Thank you!!
