### ISSUE TITLE
The default client has 30 seconds timeout

### ISSUE THREAD

**Issue by dilawar** [malaire/ml-downloader#2]
See https://github.com/seanmonstar/reqwest/issues/1343

Downloading large files will fail without an public API to tweak the timeout!

**Comment by malaire** [comment]
I think this should work, or do you need to change this for each download?

```
use ml_downloader::Downloader;

let mut downloader = Downloader::builder()
    .reqwest(|cb| cb.timeout(None)) // or whatever timeout you want
    .build()?;
```

**Comment by dilawar** [comment]
This will work just fine for me. Thanks for such quick help.
